--- 
source: 
  base_path: /
  system_id: data-sd2e-community
destination: 
  base_path: /temp/flow_etl/launch_fcs_etl_app/
  system_id: data-sd2e-community
job_params:
  data_subdir: instrument_output
  output_subdir: processed
job_definition:
  name: ~
  inputs: ~
  archiveSystem: ~
  archivePath: ~
  appId: jeg-fcs-etl-0.3.3
  batchQueue: normal
  maxRunTime: '00:55:00'
  archive: true
  notifications:
  - url: https://hookb.in/Z6Om4Ob1?job_id=${JOB_ID}&status=${JOB_STATUS}
    event: "*"
    persistent: true
  - url: jed.singer@twosixlabs.com
    event: FINISHED
    persistent: false
  - url: jed.singer@twosixlabs.com
    event: FAILED
    persistent: false
